import { describe, it, expect } from "vitest"
import {
  applyRecalibrator,
  buildDesign,
  compareCalibrators,
  fitLogistic,
  fitRecalibrator,
  logit,
  sigmoid,
} from "../../src/decisions/recalibrate"
import type { GradedRow } from "../../src/decisions/store"

function mulberry32(seed: number) {
  return () => {
    seed |= 0
    seed = (seed + 0x6d2b79f5) | 0
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function row(confidence: number, correct: boolean, features: Record<string, string> = {}): GradedRow {
  return {
    callId: "c", seat: "s", ts: 0, backend: "mock", model: "m", structureMode: "mock",
    question: "q", type: "noul", predicted: "yes", confidence,
    probabilities: { yes: confidence, no: 1 - confidence },
    truth: correct ? "yes" : "no",
    features, mode: "shadow", explored: false,
  }
}

describe("link functions", () => {
  it("logit and sigmoid round-trip", () => {
    for (const p of [0.01, 0.2, 0.5, 0.8, 0.99]) {
      expect(sigmoid(logit(p))).toBeCloseTo(p, 10)
    }
  })

  it("clamps rather than returning infinity at the boundaries", () => {
    expect(Number.isFinite(logit(0))).toBe(true)
    expect(Number.isFinite(logit(1))).toBe(true)
    expect(sigmoid(-1000)).toBe(0)
    expect(sigmoid(1000)).toBe(1)
  })
})

describe("fitLogistic", () => {
  it("recovers known weights from data generated by them", () => {
    const rng = mulberry32(1)
    const trueW = [-0.7, 1.6]
    const X: number[][] = []
    const y: number[] = []
    for (let i = 0; i < 4000; i++) {
      const x = (rng() - 0.5) * 6
      X.push([1, x])
      y.push(rng() < sigmoid(trueW[0] + trueW[1] * x) ? 1 : 0)
    }
    const w = fitLogistic(X, y, { l2: 1e-6 })
    expect(w[0]).toBeCloseTo(trueW[0], 1)
    expect(w[1]).toBeCloseTo(trueW[1], 1)
  })

  it("does not blow up on a perfectly separable column", () => {
    const X = Array.from({ length: 50 }, (_, i) => [1, i < 25 ? 1 : 0])
    const y = X.map((r) => (r[1] === 1 ? 1 : 0))
    const w = fitLogistic(X, y)
    // Unregularised this diverges. The ridge keeps it finite.
    expect(w.every((v) => Number.isFinite(v))).toBe(true)
    expect(Math.abs(w[1])).toBeLessThan(50)
  })

  it("returns zeros on empty input rather than throwing", () => {
    expect(fitLogistic([], [])).toEqual([])
  })
})

describe("buildDesign", () => {
  it("drops one level per covariate as the reference", () => {
    const rows = [
      ...Array.from({ length: 10 }, () => row(0.8, true, { agent: "a" })),
      ...Array.from({ length: 10 }, () => row(0.8, true, { agent: "b" })),
      ...Array.from({ length: 10 }, () => row(0.8, true, { agent: "c" })),
    ]
    const design = buildDesign(rows, { covariates: ["agent"] })
    // 3 levels -> 2 columns, plus intercept and the confidence term.
    expect(design.names).toEqual(["intercept", "logitConfidence", "agent=b", "agent=c"])
    expect(design.X[0]).toHaveLength(4)
  })

  it("folds rare levels into the reference rather than giving them a parameter", () => {
    const rows = [
      ...Array.from({ length: 30 }, () => row(0.8, true, { agent: "common" })),
      ...Array.from({ length: 30 }, () => row(0.8, true, { agent: "also-common" })),
      row(0.8, true, { agent: "seen-once" }),
    ]
    const design = buildDesign(rows, { covariates: ["agent"], minLevelCount: 5 })
    expect(design.names).not.toContain("agent=seen-once")
  })

  it("reads covariates from the row itself when not in features", () => {
    const rows = [
      ...Array.from({ length: 10 }, () => ({ ...row(0.8, true), question: "a" })),
      ...Array.from({ length: 10 }, () => ({ ...row(0.8, true), question: "b" })),
    ]
    const design = buildDesign(rows, { covariates: ["question"] })
    expect(design.names).toContain("question=b")
  })
})

describe("fitRecalibrator with no covariates", () => {
  it("corrects an overconfident generator to its true accuracy", () => {
    const rng = mulberry32(2)
    // Always claims 0.9, right 65% of the time.
    const rows = Array.from({ length: 2000 }, () => row(0.9, rng() < 0.65))
    const model = fitRecalibrator(rows, { covariates: [] })
    expect(applyRecalibrator(model, row(0.9, true))).toBeCloseTo(0.65, 1)
  })

  it("leaves a well-calibrated generator roughly alone", () => {
    const rng = mulberry32(3)
    const rows = Array.from({ length: 3000 }, () => {
      const c = 0.5 + rng() * 0.5
      return row(c, rng() < c)
    })
    const model = fitRecalibrator(rows, { covariates: [] })
    for (const c of [0.6, 0.75, 0.9]) {
      expect(applyRecalibrator(model, row(c, true))).toBeCloseTo(c, 1)
    }
  })
})

describe("compareCalibrators", () => {
  /** Two agents whose calibration genuinely differs: one honest, one wildly
   *  overconfident. A single temperature has to average them. */
  function heterogeneous(n: number, rng: () => number): GradedRow[] {
    return Array.from({ length: n }, () => {
      const agent = rng() < 0.5 ? "honest" : "bluffer"
      const claimed = 0.9
      const actual = agent === "honest" ? 0.88 : 0.45
      return row(claimed, rng() < actual, { agent })
    })
  }

  /** Same calibration in both groups — the covariate carries no signal. */
  function homogeneous(n: number, rng: () => number): GradedRow[] {
    return Array.from({ length: n }, () => {
      const agent = rng() < 0.5 ? "a" : "b"
      return row(0.9, rng() < 0.65, { agent })
    })
  }

  it("picks the covariate model when calibration really does differ by group", () => {
    const rows = heterogeneous(1500, mulberry32(4))
    const result = compareCalibrators(rows, { covariates: ["agent"] }, { rng: mulberry32(5) })

    expect(result.insufficient).toBe(false)
    expect(result.best).toBe("covariate")

    const byName = Object.fromEntries(result.scores.map((s) => [s.name, s.logLoss]))
    expect(byName.covariate).toBeLessThan(byName.temperature)
    expect(byName.temperature).toBeLessThan(byName.raw)
  })

  it("recovers per-group calibration the global fit cannot express", () => {
    const rows = heterogeneous(3000, mulberry32(6))
    const model = fitRecalibrator(rows, { covariates: ["agent"] })
    const honest = applyRecalibrator(model, row(0.9, true, { agent: "honest" }))
    const bluffer = applyRecalibrator(model, row(0.9, true, { agent: "bluffer" }))
    expect(honest).toBeGreaterThan(0.75)
    expect(bluffer).toBeLessThan(0.6)
  })

  it("does NOT pick the covariate model when the covariate is noise", () => {
    // The test that makes the rest trustworthy: more parameters always fit
    // the training data better, so a comparison that always says "use the
    // bigger model" is worthless.
    const rows = homogeneous(1500, mulberry32(7))
    const result = compareCalibrators(rows, { covariates: ["agent"] }, { rng: mulberry32(8) })
    expect(result.best).not.toBe("covariate")
  })

  it("refuses to compare below minN", () => {
    const rows = homogeneous(60, mulberry32(9))
    const result = compareCalibrators(rows, { covariates: ["agent"] }, { minN: 100 })
    expect(result.insufficient).toBe(true)
    expect(result.scores).toEqual([])
    expect(result.best).toBeUndefined()
  })

  it("ignores unlabeled rows", () => {
    const labeled = homogeneous(150, mulberry32(10))
    const unlabeled = Array.from({ length: 500 }, () => ({ ...row(0.9, true), truth: undefined }))
    const result = compareCalibrators([...labeled, ...unlabeled], { covariates: [] }, { minN: 100 })
    expect(result.n).toBe(150)
  })
})

describe("applyRecalibrator", () => {
  it("falls back to the reference level for a group it never saw", () => {
    const rows = [
      ...Array.from({ length: 100 }, (_, i) => row(0.9, i % 2 === 0, { agent: "a" })),
      ...Array.from({ length: 100 }, (_, i) => row(0.9, i % 4 !== 0, { agent: "b" })),
    ]
    const model = fitRecalibrator(rows, { covariates: ["agent"] })
    const unseen = applyRecalibrator(model, row(0.9, true, { agent: "brand-new" }))
    expect(Number.isFinite(unseen)).toBe(true)
    expect(unseen).toBeGreaterThan(0)
    expect(unseen).toBeLessThan(1)
  })

  it("is monotonic in confidence", () => {
    const rng = mulberry32(11)
    const rows = Array.from({ length: 800 }, () => {
      const c = 0.5 + rng() * 0.5
      return row(c, rng() < c)
    })
    const model = fitRecalibrator(rows, { covariates: [] })
    const low = applyRecalibrator(model, row(0.55, true))
    const high = applyRecalibrator(model, row(0.95, true))
    expect(high).toBeGreaterThan(low)
  })
})
