// Writes every native AgentX icon from the AX symbol (src/brand/ax-symbol.ts).
//
//   npx tsx scripts/gen-icons.ts           write the icons
//   npx tsx scripts/gen-icons.ts --check   exit 1 if any icon is out of date
//
// The daemon's web icons are drawn at runtime from the same points, so
// they need nothing here. See #686.

import { mkdirSync, readFileSync, writeFileSync } from "fs"
import { dirname, join } from "path"
import { fileURLToPath } from "url"
import { inflateSync } from "zlib"
import { AX_INK, AX_LAYOUT, AX_PAPER, axIconSvg, axSymbolPathData } from "../src/brand/ax-symbol"
import { renderIconPng } from "../src/daemon/app-icon"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const GENERATED = "Generated by scripts/gen-icons.ts from src/brand/ax-symbol.ts. Do not edit."

const files = new Map<string, string | Buffer>()

// Android: an adaptive icon, the symbol inside the 66dp safe zone so a round
// or squircle mask never cuts it. The same foreground is the monochrome
// layer for themed icons. Legacy PNGs for launchers that ask for them.
const foreground = `<?xml version="1.0" encoding="utf-8"?>
<!-- ${GENERATED} -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <path android:fillColor="@color/ax_launcher_ink"
        android:pathData="${axSymbolPathData(108, AX_LAYOUT.android)}" />
</vector>
`
const adaptive = `<?xml version="1.0" encoding="utf-8"?>
<!-- ${GENERATED} -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ax_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
`
const colors = `<?xml version="1.0" encoding="utf-8"?>
<!-- ${GENERATED} -->
<resources>
    <color name="ax_launcher_background">${AX_PAPER.toUpperCase()}</color>
    <color name="ax_launcher_ink">${AX_INK.toUpperCase()}</color>
</resources>
`
const DENSITIES: [string, number][] = [["mdpi", 48], ["hdpi", 72], ["xhdpi", 96], ["xxhdpi", 144], ["xxxhdpi", 192]]
for (const res of ["apps/android/app/src/main/res", "apps/phone/android/app/src/main/res"]) {
  files.set(`${res}/drawable/ic_launcher_foreground.xml`, foreground)
  files.set(`${res}/mipmap-anydpi-v26/ic_launcher.xml`, adaptive)
  files.set(`${res}/values/ic_launcher_colors.xml`, colors)
  if (res.startsWith("apps/phone")) {
    for (const [d, px] of DENSITIES) files.set(`${res}/mipmap-${d}/ic_launcher.png`, renderIconPng({ size: px, width: AX_LAYOUT.safe, background: "square" }))
  }
}

// iOS (Flutter app): every size its asset catalog lists. iOS rounds the
// corners itself, so these are full squares.
const appiconset = "apps/phone/ios/Runner/Assets.xcassets/AppIcon.appiconset"
const catalog = JSON.parse(readFileSync(join(ROOT, appiconset, "Contents.json"), "utf8")) as { images: { size: string; scale: string; filename?: string }[] }
for (const img of catalog.images) {
  if (!img.filename) continue
  const px = Math.round(parseFloat(img.size) * parseFloat(img.scale))
  files.set(`${appiconset}/${img.filename}`, renderIconPng({ size: px, width: AX_LAYOUT.full, background: "square" }))
}

// Mac apps and Raycast: Apple's rounded square on a transparent canvas.
const mac = renderIconPng({ size: 1024, width: AX_LAYOUT.mac, background: "mac" })
files.set("apps/mac-helper/Resources/AppIcon.png", mac)
files.set("apps/mac-voice/Resources/AppIcon.png", mac)
files.set("integrations/raycast/assets/icon.png", renderIconPng({ size: 512, width: AX_LAYOUT.mac, background: "mac" }))

// The docs' spare SVG favicons, so no older mark lingers.
for (const f of ["docs/public/favicon.svg", "docs-holding/favicon.svg"]) files.set(f, axIconSvg() + "\n")

// PNGs are compared by header and pixels, not bytes: zlib builds differ
// between Node versions and compress the same pixels differently.
function same(a: Buffer, b: Buffer): boolean {
  if (a.equals(b)) return true
  const pa = pngPixels(a)
  const pb = pngPixels(b)
  return !!pa && !!pb && pa.equals(pb)
}

function pngPixels(png: Buffer): Buffer | null {
  if (png.subarray(1, 4).toString() !== "PNG") return null
  const parts: Buffer[] = []
  let ihdr: Buffer | null = null
  for (let o = 8; o + 8 <= png.length; ) {
    const len = png.readUInt32BE(o)
    const type = png.subarray(o + 4, o + 8).toString("ascii")
    const data = png.subarray(o + 8, o + 8 + len)
    if (type === "IHDR") ihdr = data
    if (type === "IDAT") parts.push(data)
    o += 12 + len
  }
  try {
    return ihdr ? Buffer.concat([ihdr, inflateSync(Buffer.concat(parts))]) : null
  } catch {
    return null // not a PNG we can read: treat as different
  }
}

const check = process.argv.includes("--check")
const stale: string[] = []
for (const [rel, body] of files) {
  const path = join(ROOT, rel)
  let current: Buffer | null = null
  try { current = readFileSync(path) } catch { /* new file */ }
  if (current && same(current, Buffer.from(body))) continue
  stale.push(rel)
  if (!check) {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, body)
  }
}
if (check && stale.length) {
  process.stderr.write(`Out of date (run npx tsx scripts/gen-icons.ts):\n${stale.map((f) => `  ${f}\n`).join("")}`)
  process.exit(1)
}
process.stdout.write(check ? `${files.size} icons up to date\n` : `${stale.length} of ${files.size} icons written\n`)
